/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IMaterialSymbols10k: typeof import('~icons/material-symbols/10k')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IRi24HoursLine: typeof import('~icons/ri/24-hours-line')['default']
    IRi24Outline: typeof import('~icons/ri/24-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserComponent: typeof import('./src/components/user/UserComponent.vue')['default']
  }
}
